name: "Deploy package"

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    permissions:
      id-token: write
      contents: read
      repository-projects: read
      packages: read

    runs-on: ubuntu-latest
    container:
      image: ghcr.io/goldenm-software/python-builder:uv-3.13-x86
      options: --user root
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Build and upload
        run: |
          uv venv --python 3.13
          uv sync --only-group dev
          uv run python -m build
          uv run python -m twine upload -u ${{ secrets.GOLDENM_PYPI_USERNAME }} -p ${{ secrets.GOLDENM_PYPI_PASSWORD }} dist/*
